# Generated by Django 2.1.3 on 2018-12-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'locators',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='locators',
            field=models.ManyToManyField(to='books.Locator'),
        ),
    ]
