# Generated by Django 2.1.3 on 2018-12-11 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20181211_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('locator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Locator')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
    ]
